import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
    build: {
        rollupOptions: {
            input: {
                main: resolve(__dirname, 'index.html'),
                login: resolve(__dirname, 'login.html'),
                dashboard: resolve(__dirname, 'dashboard.html'),
                serviciosValores: resolve(__dirname, 'servicios-y-valores.html'),
                capacitacion: resolve(__dirname, 'capacitacion.html'),
                direccionLaboral: resolve(__dirname, 'direccion-laboral-externa.html'),
                queEsOmnes: resolve(__dirname, 'que-es-omnes.html'),
                paraQuien: resolve(__dirname, 'para-quien-es.html'),
                beneficios: resolve(__dirname, 'beneficios.html'),
                mision: resolve(__dirname, 'mision.html'),
                contacto: resolve(__dirname, 'contacto.html'),
                personas: resolve(__dirname, 'personas.html'),
                personasLogin: resolve(__dirname, 'personas-login.html'),
                personasRegistro: resolve(__dirname, 'personas-registro.html'),
                personasDashboard: resolve(__dirname, 'personas-dashboard.html'),
                personasCv: resolve(__dirname, 'personas-cv.html'),
                personasCarta: resolve(__dirname, 'personas-carta.html'),
                personasDocumentos: resolve(__dirname, 'personas-documentos.html'),
                personasRenuncia: resolve(__dirname, 'personas-renuncia.html'),
                personasOfertas: resolve(__dirname, 'personas-ofertas.html'),
                personasOfertaDetalle: resolve(__dirname, 'personas-oferta-detalle.html'),
                personasFavoritos: resolve(__dirname, 'personas-favoritos.html'),
                personasPerfilPublico: resolve(__dirname, 'personas-perfil-publico.html'),
                empresa: resolve(__dirname, 'empresa.html'),
                empresaLogin: resolve(__dirname, 'empresa-login.html'),
                empresaRegistro: resolve(__dirname, 'empresa-registro.html'),
                empresaDashboard: resolve(__dirname, 'empresa-dashboard.html'),
                empresaPerfil: resolve(__dirname, 'empresa-perfil.html'),
                empresaNuevaOferta: resolve(__dirname, 'empresa-nueva-oferta.html'),
                empresaOfertas: resolve(__dirname, 'empresa-ofertas.html'),
                empresaPostulaciones: resolve(__dirname, 'empresa-postulaciones.html'),
                empresaPublico: resolve(__dirname, 'empresa-publico.html'),
                empresaConfiguracion: resolve(__dirname, 'empresa-configuracion.html'),
                adminLogin: resolve(__dirname, 'admin/login.html'),
                adminDashboard: resolve(__dirname, 'admin/dashboard.html'),
                adminUsuarios: resolve(__dirname, 'admin/usuarios.html'),
                adminEmpresas: resolve(__dirname, 'admin/empresas.html'),
                adminOfertas: resolve(__dirname, 'admin/ofertas.html'),
                adminComunidad: resolve(__dirname, 'admin/comunidad.html'),
                adminIngresos: resolve(__dirname, 'admin/ingresos.html'),
                adminOpenomnes: resolve(__dirname, 'admin/openomnes.html'),
                adminDocumentos: resolve(__dirname, 'admin/documentos.html'),
                adminDocumentosRecibidos: resolve(__dirname, 'admin/documentos-recibidos.html'),
                adminFiniquitos: resolve(__dirname, 'admin/finiquitos.html'),
                adminEstadisticas: resolve(__dirname, 'admin/estadisticas.html'),
                comunidad: resolve(__dirname, 'comunidad.html'),
                comunidadDetalle: resolve(__dirname, 'comunidad-detalle.html'),
                personasAnalisisFiniquito: resolve(__dirname, 'personas-analisis-finiquito.html'),
                servicios: resolve(__dirname, 'servicios.html'),
                herramientas: resolve(__dirname, 'herramientas.html'),
                calculadoraFiniquito: resolve(__dirname, 'calculadora-finiquito.html'),
                calculadoraVacaciones: resolve(__dirname, 'calculadora-vacaciones.html'),
                calculadoraIndemnizacion: resolve(__dirname, 'calculadora-indemnizacion.html'),
                empresaCandidatos: resolve(__dirname, 'empresa-candidatos.html'),
                candidatoDetalle: resolve(__dirname, 'candidato-detalle.html'),
                mensajes: resolve(__dirname, 'mensajes.html'),
                ayuda: resolve(__dirname, 'ayuda.html'),
                terminos: resolve(__dirname, 'terminos.html'),
                privacidad: resolve(__dirname, 'privacidad.html'),
                comunidadRanking: resolve(__dirname, 'comunidad-ranking.html'),
                feed: resolve(__dirname, 'feed.html'),
                invitar: resolve(__dirname, 'invitar.html'),
                pagoExitoso: resolve(__dirname, 'pago-exitoso.html'),
                blog: resolve(__dirname, 'blog.html'),
                ofertasSeo: resolve(__dirname, 'ofertas-seo.html'),
                derechosLaborales: resolve(__dirname, 'derechos-laborales.html'),
                derechosDetalle: resolve(__dirname, 'derechos-detalle.html'),
                calculadoraSueldoLiquido: resolve(__dirname, 'calculadora-sueldo-liquido.html'),
                calculadorasLaboralesChile: resolve(__dirname, 'calculadoras-laborales.html'),
                personasPostulaciones: resolve(__dirname, 'personas-postulaciones.html'),
                empresaMetricas: resolve(__dirname, 'empresa-metricas.html'),
                empresaPlanes: resolve(__dirname, 'empresa-planes.html'),
                empresaPublica: resolve(__dirname, 'empresa-publica.html'),
                ofertasCiudad: resolve(__dirname, 'ofertas-ciudad.html'),
                empresas: resolve(__dirname, 'empresas.html'),
            },
        },
    },
    server: {
        proxy: {
            '/api': {
                target: 'http://127.0.0.1:8788',
                changeOrigin: true,
                secure: false,
            }
        }
    }
});
